### ISSUE TITLE
Multiple Option labels?

### ISSUE THREAD

**Issue by EliasChampi** [robrogers3/vue-single-select#1]
Hey there, Great plugin, thank you for your hard work.
I have a question,

I have a drop down which is listing multiple users, they are in an array, with first name, last name and email all separate.

I want to make the option label;
So that the label is all three, instead of one.

I used your template slot to make it show on the dropdown, but is there any way to allow it to come up on the label too?
Thanks!

**Comment by robrogers3** [comment]
Yeah you can use the prop:getOptionDescription

Just write a function in the parent component and pass it in as a prop. 

In the method you write you can return anything you want 

If you need some code to get started let me know. 

 

Rob Rogers 
robrogers@me.com

**Comment by EliasChampi** [comment]
Thanks its work
my function is  
    getOptionDescription (item) {
      return item.name + " " + item.lastName 
    },

**Comment by robrogers3** [comment]
Sorry, I missed this. Can you elaborate on what you mean by filterable was disabled?

Can you show me how you are using it. i.e.
<vue-single-select>
   prop-a=a
</vue-single-select>

**Comment by robrogers3** [comment]
old.
