### ISSUE TITLE
cannot enter new value in the only takes from what is in the list 

### ISSUE THREAD

**Issue by sanfx** [robrogers3/vue-single-select#12]
if I enter a text that doesnt exist in the list, on loose focus it goes away so I wonder how we get the value of the text enter, because the value `v-model: storeValue` will not store the value , so I implemented that if user enter Enter key it should append to the list and set as well but even using jQuery I am not able to get anything:

    $(document).ready(function(){
        $("#inputPatientName").on("keyup", function(e){
            if (e.keyCode == 13) {
                console.log("You hit enter ?" + $('inputPatientName').val());
            }
        });
    });

in the above function `$('inputPatientName').val()` returns undefined.
if I use vue approach to read the value from storeValue that too says undefined.

Please help me with this

**Comment by robrogers3** [comment]
why are you using Jquery?

can you show me your Vue code?
----------------------------------
Rob Rogers
415.615.2859
robrogers@me.com
----------------------------------

**Comment by robrogers3** [comment]
close due no response
