### ISSUE TITLE
Browser autocomplete problem

### ISSUE THREAD

**Issue by lasthead** [robrogers3/vue-single-select#14]
Hello,
Thank you, it's a very good vue-component!
But when I put settings autocomplete="off", Chrome still fills in the saved value. The block with value overlaps list options, and user can't choose option when he enters the text

![image](https://user-images.githubusercontent.com/43372353/53081304-a1625800-350b-11e9-9eed-fb2d5dbee209.png)

![w3xs2z7](https://user-images.githubusercontent.com/43372353/53082401-d2dc2300-350d-11e9-9f40-128e021663c8.gif)

**Comment by lasthead** [comment]
I copy component in my local space and add to input autocomplete="new-city". It helped to me.
Perhaps you need to make it possible to add a value for "autocomplete" to solve this problem. This as one way

**Comment by robrogers3** [comment]
humm, chrome does this to me too on many sites.

Really annoying.

I'll take a look now.

**Comment by robrogers3** [comment]
Quick question, can you share your "html" for the component?
And what version of chrome are you using?

Note if you use autocomplete off in the component usage that won't work.
i.e. this won't work.
`
<vue-single-select
...
autocomplete="off"
></vue-single-select>
`

however you could add it to the form.

but, in fact, autocomplete=off is baked into the component.

**Comment by imkremen** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=468153#c164

**Comment by lasthead** [comment]
@robrogers3 ,
Here is my html for the component:
```
<vue-single-select
            id="city"
            v-model="selectCity"
            you-want-to-select-a-reply="yes"
            :options="getCityList"
            :getOptionDescription="getOptionDescription"
            :required="true"
            option-key="CITY_ID"
            option-label="CITY_NAME"
            name="city"
            :initial="'Москва'"
            :maxResults="1500"
            :value=745
            placeholder="Выберите город"
            seed-an-initial-value="Москва"
            ref="selectCity"
          >
```

I tried adding `autocomplete="off"` to `<form>`, but problem still the same 

![2019-02-22_16-52-13](https://user-images.githubusercontent.com/43372353/53246707-75d59e00-36c2-11e9-8e87-f3a059ba6ee8.gif)

**Comment by robrogers3** [comment]
What's tough for me here is that I cannot recreate this. autocomplete=off works.

can you send me App.vue or whatever file uses this component?
create a tarball or attach the file in some manner.

also which version of chrome are you using?
the bug you list is from 2015

**Comment by robrogers3** [comment]
@lasthead i haven't heard from you so closing.
