### ISSUE TITLE
How to bind v-model

### ISSUE THREAD

**Issue by jozeflambrecht** [robrogers3/vue-single-select#15]
Hi Rob,
First of all, thank you for this package. I am using Laravel and want to replace all select menus with your component. Please find my code to assign a user to a post:
edit.blade.php
```
<vue-single-select
        name="user_id"
        v-model="post.user_id"
        placeholder="Select user"
        :options="{!! $users !!}"
        option-key="id"
        option-label="name"
></vue-single-select>
```
app.js
```
import VueSingleSelect from "vue-single-select";
Vue.component('vue-single-select', VueSingleSelect);
```
The search box is working, but I get this error in the console: 
`Property or method "user" is not defined on the instance but referenced during render.`
I would like to bind the current `$post->user_id` to the component when editing (and a `null` value when creating a new post).

Hope that makes sense to you.

**Comment by jozeflambrecht** [comment]
I think I am closer to a solution (learning Vue!):
UsersComponent.vue
```
<template>
    <vue-single-select      
        v-model="post"
        :options="users"
        :required="true"
        option-label="name"
        option-key="id"
        name="user_id"
    ></vue-single-select>
</template>

<script>
    import VueSingleSelect from "vue-single-select";
    export default {
        components: {
            VueSingleSelect
        },
        props: ['post', 'users'],
    }
</script>
```
blade:
```
<users-component
        :post="{{ $post->toJson() }}"
        :users="{{ $users }}"
      ></users-component>
```
It is working (without errors in console), but when I edit the post, I do not see the v-model value as selected. Any thoughts? And how could I use this when I create a new post (so no post model available).

Thanks!

**Comment by robrogers3** [comment]
A couple things:
1.  You do not have a data.post property. so, the thing (post) you want to set does not exist in your component. you cannot use props.post. you need to have something mutable in the data portion of your component and then on change do something with it. like propagate the change up the component chain.
2. And I'm confused by this. Out of your list of options (users), you want to select a post.ID?  Shouldn't it be a user.id?  or post.user_id ? 

A normal scenario would be :options = posts, v-model=post. optionLabel=title optionValue=id.

Can you describe your scenario in more detail.  LIke:
* my component should allow someone to assign a post to a user.
* it should show a list of user ids, and a post.
* on change, the post user_id should be set to the selected user.
* ...

Also, make sure you have the Vue chrome debug plugin installed.

**Comment by jozeflambrecht** [comment]
Thank you for your answer! So here is the scenario: I have a Post model and a User model. (Post belongsTo User relation). So when I create or edit a (blog) post, I want a dropdown with all users, so I can assign the reviewer. The options are the users, optionLabel=name (username), optionValue=id (user ID).
When I edit the post, the value of the search field with name="user_id" should be the current post.user_id.
On change, the value of the search field with name="user_id" should be the selected user id.

I changed `v-model="post"` to `v-model="post.user_id"` and I moved the user property to data:

```
        props: ['users'],
        data() {
            return {
                post: this.post
            };
        },
```
But it still does not bind the post.user_id. Let me know if you understand my scenario!

**Comment by robrogers3** [comment]
First, what does the Vue debug tool say for the SingleSelect component selectedOption on Change.
2nd, on mount, what does your component say for the value of data.user?
3rd, what does the 'html' look like for your use of <vue-single-select>blah</vue-single-select>
4th, meh, just tarball up and try to attach your code. i'll try to fix.

**Comment by robrogers3** [comment]
oh, and another note, on select (change), the data.user should be the ENTIRE user object, not just the user_id.  

also, based on your usage, non-trivial, you shouldn't care about the 'user_id' being set to the hidden field, unless you are doing a real post back instead of ajax.

**Comment by jozeflambrecht** [comment]
hi Rob, it works with the ENTIRE object! Thanks man!

**Comment by robrogers3** [comment]
awesome, glad to here. let me know how the usage goes on other parts of site.
one problem I have is when one is stacked right on top of another one -- if they are seeded with an initial value. let me know if you have problems here.
