### ISSUE TITLE
Disabled feature

### ISSUE THREAD

**Issue by mrFANRA** [robrogers3/vue-single-select#16]
Hi! Thanks for you package!

Please, can you add "disabled" feature in new versions?

**Comment by robrogers3** [comment]
Good call 

Rob Rogers 
robrogers@me.com

**Comment by KattemChen** [comment]
I also encountered a similar situation, I hope to add a function that prohibits writing.

**Comment by robrogers3** [comment]
@mrFANRA @KattemChen 
done
