### ISSUE TITLE
Show value from update

### ISSUE THREAD

**Issue by fabien44300** [robrogers3/vue-single-select#2]
Hello,
Thank you, it's a very good template I used to fill a field.
The problem is when I want to use again the template to show the new value I created to update it by example. I don't find how to return my value, it always show the placeholder 

              <vue-single-select
                                v-model="oauthclient.user_id"
                                :options="users"
                                :required="false"
                                option-label="name"
                        ></vue-single-select>

How can I do that : If my oauthclient.user_id is not null, show my option-label  from value. Else show the placeholder ?

Regards

Fabien

**Comment by robrogers3** [comment]
Okay, let me restate the problem:

WHEN you use vue-single-select, 
AND the v-model has a value that is not null,
THEN you should see the v-model value selected in the drop down.

However, currently you don't see the the v-model value as selected.

Is this correct?

**Comment by fabien44300** [comment]
I should see the name in the drop down (option-label="name")
Example : 

- my options is users ( 'id' =1 , 'name' = 'john' ; id= 2", 'name' = 'donald')

- my v-model is oauthclient.user_id with value 2 (user_id is the foreign key linked to the primary key 'id" from  users model )

I should see 'Donald' , Donald must be the option selected because value is 2.

**Comment by robrogers3** [comment]
Update the package. And try:


        <vue-single-select      
            v-model=“oauthclient.user_id"
            :options=“users"
            option-label=“name"
            option-key="id"
        ></vue-single-select>    

let me know if it works
----------------------------------
Rob Rogers
415.615.2859
robrogers@me.com
----------------------------------

**Comment by robrogers3** [comment]
Can I close this?
----------------------------------
Rob Rogers
415.615.2859
robrogers@me.com
----------------------------------

**Comment by fabien44300** [comment]
Yes you can close this.
Thank you.

**Comment by robrogers3** [comment]
Closed based on user input

**Comment by jozeflambrecht** [comment]
@fabien44300 I have the same problem. Can you please tell me how you solved your problem with a code example?

**Comment by fabien44300** [comment]
Hello jozeflambrecht, 
I don't use this package now  (I prefer use Vuetify) and I don't remember the code but the solution is to not use the foreign key field as v-model. You have to use the foreign key model as v-model.
A way is to call the relationship model in your model.

Example in Laravel :
User::find(1)->with('post') 
in the v-model of this package, don't set  user.post_id but user.post 

I hope it could help you.

**Comment by robrogers3** [comment]
This sounds correct. 

Rob Rogers 
robrogers@me.com
