### ISSUE TITLE
Invalid prop: type check failed for prop "options". Expected Array, got String with value ""

### ISSUE THREAD

**Issue by damisadam** [robrogers3/vue-single-select#27]
[Vue warn]: Invalid prop: type check failed for prop "options". Expected Array, got String with value "".

found in

---> <VueSingleSelect> at VueSingleSelect.vue
       <Root>

Select is 
`<vue-single-select
                                            v-model="invoiceForm.customer"
                                            :options="ajaxCustomers"
                                            option-label="FullName"
                                            :max-results="1500"
                                    ></vue-single-select>`

And Data is

ajaxCustomers=[
0: {FullName: "Jimmy11", ListID: "80000001-1428315359", BillAddress_Addr1: "RocketDrop-HK",…}
1: {FullName: "Tom Cruise", ListID: "80000001-1470054554", BillAddress_Addr1: "Hollywood",…}
2: {FullName: "Zeshan", ListID: "80000001-1493279891", BillAddress_Addr1: "Islamabad",…}
3: {FullName: "JimmyShah", ListID: "80000002-1428329683", BillAddress_Addr1: "", BillAddress_Addr2: "",…}
4: {FullName: "Asim", ListID: "80000002-1479745328", BillAddress_Addr1: "NXB", BillAddress_Addr2: "0",…}
5: {FullName: "Jalil Khan Ch", ListID: "80000002-1486116870", BillAddress_Addr1: "Nextbridge",…}
6: {FullName: "Ebay", ListID: "80000002-1496389315", BillAddress_Addr1: "0", BillAddress_Addr2: "0",…}
7: {FullName: "Ebay", ListID: "80000002-1538141362", BillAddress_Addr1: "0", BillAddress_Addr2: "0",…}
8: {FullName: "Adnan", ListID: "80000003-1479811858", BillAddress_Addr1: "Adnan Int",…}
9: {FullName: "zeeshan", ListID: "80000004-1450176881", BillAddress_Addr1: "RocketDrop-UAE",…}
10: {FullName: "Abubakar", ListID: "80000004-1479814506", BillAddress_Addr1: "0", BillAddress_Addr2: "0",…}
11: {FullName: "eBay corp", ListID: "80000004-1496399973", BillAddress_Addr1: "0", BillAddress_Addr2: "0",…}
12: {FullName: "Customer 1", ListID: "80000005-1493293313", BillAddress_Addr1: "0", BillAddress_Addr2: "0",…}
13: {FullName: "eBay", ListID: "80000006-1493385335", BillAddress_Addr1: "0", BillAddress_Addr2: "0",…}
14: {FullName: "eBay corp", ListID: "80000008-1494413649", BillAddress_Addr1: "0", BillAddress_Addr2: "0",…}
]

I am unable to resolve this. there is no String value. array is provided.

**Comment by robrogers3** [comment]
Remove the indexes from your array of customers. Currently it’s not a valid array.
---------------------------
Robert Rogers
415.615.2859
robrogers@me.com
---------------------------

**Comment by damisadam** [comment]
@robrogers3  
I simply add this.
[{id: 1, name: "DHL"}, {id: 2, name: "Federal Express"}]
 but the  error is same. :(

**Comment by damisadam** [comment]
I solve this one:-
 The array is valid but my initial value is a string like

data: function () {
                return {
                    ajaxCustomers:'',
                    loading: false
                }
            },

I just update to this one to array.

data: function () {
                return {
                    ajaxCustomers:[],
                    loading: false
                }
            },

**Comment by robrogers3** [comment]
gotcha!
