### ISSUE TITLE
How to call a function on value change. 

### ISSUE THREAD

**Issue by damisadam** [robrogers3/vue-single-select#28]
<vue-single-select
                            placeholder="Search on-hold"
                            v-model="selected"
                            @change="getDetail()"
                            :options="ajaxInvoice"
                            option-label="title"
                    ></vue-single-select>

I want to call a function on value change. Please share which method  I use for this

**Comment by robrogers3** [comment]
If you’re interested in when it changes. 

Use vue watch:
https://vuejs.org/v2/guide/computed.html

You can also check on @input but that’s a pain.

---------------------------
Robert Rogers
415.615.2859
robrogers@me.com
---------------------------

**Comment by damisadam** [comment]
Thank you!! @robrogers3

**Comment by robrogers3** [comment]
closed with thanks!
