### ISSUE TITLE
non-unique id #single-select and #input_id

### ISSUE THREAD

**Issue by fabien44300** [robrogers3/vue-single-select#5]
Hello,
I use 2  vue-single-select in the same Vue but each vue-single-select keep the same id : 

[DOM] Found 2 elements with non-unique id #single-select
 <input data-v-27213e1d id=​"single-select"....>

So, I overrided  inputId : 

     <vue-single-select
     id="scope_webservice_update"
    inputId="scope_webservice_update_inputId"
   ........
  ></vue-single-select>

It is ok : 

<div data-v-27213e1d="" id="scope_webservice_update"><div data-v-27213e1d="" class="single-select-wrapper">
<input data-v-27213e1d="" id="scope_webservice_update_inputId".....

But on clicking to the single-vue-select to choose an option in the view , it's strange, but the id  automatically change to "inputId" and override "scope_webservice_update_inputId"

DOM] Found 2 elements with non-unique id #inputId: 

<div data-v-27213e1d="" id="scope_webservice_update"><div data-v-27213e1d="" class="single-select-wrapper">
<input data-v-27213e1d="" id="inputId"....

Fabien

**Comment by robrogers3** [comment]
So this: id="scope_webservice_update"
won't work, well it will put the id on the top level element, which is a div. I assume you don't want that.

I did find the problem, the code on npm is not quite up to date. I'll push the latest now.

**Comment by robrogers3** [comment]
done. please give it a try.

**Comment by robrogers3** [comment]
Why did I re-open this?
