### ISSUE TITLE
Only show matches beginning with the typed characters

### ISSUE THREAD

**Issue by vellebelle** [robrogers3/vue-single-select#6]
Hello Rob,
Thank you for writing this great component. I was wondering if it's somehow possible to only show matches that begin with the characters typed in the search box?

**Example:** If I type the letter M in the search box I will only see results beginning with the letter M - not all the results that have an M in them.
 
**Another example:** If I type 'ea' in the search box, I will see the results '**ea**rring', '**ea**r', '**ea**rth', but not the results 'p**ea**r', 'p**ea**ch', 'b**ea**r' etc..

Thanks again..

/Morten

**Comment by robrogers3** [comment]
Humm, that's a good idea. I'll check it out. Shouldn't be too hard.

**Comment by vellebelle** [comment]
Sounds great! Thank you :)

**Comment by robrogers3** [comment]
So it's done.

you will need to do something like this:
`        <vue-single-select
            ref="select"
            v-model="fruit" 
            :options="fruits"
            :filterBy="filterBy"
        ></vue-single-select>  `

then in your methods section do something like this

`
         filterBy(option) {
             const searchText = this.$refs.select.searchText
             return option
                 .toString()
                 .toLowerCase()
                 .startsWith(searchText.toString().toLowerCase())
         },
`

works for me. let me know if it works for you.

**Comment by vellebelle** [comment]
Wow, that was fast.. Thank you.. I will have a look at it tonight and get back to you ..

**Comment by robrogers3** [comment]
so is it working?

**Comment by vellebelle** [comment]
Sorry for not replying until now. I didn't get it to work by overriding the components method from the parent (App.vue) component. I could not access the "searchText" on this.$refs.select.searchText. Got a "Cannot read property … of undefined" error. 

I am also a newbie to Vue CLI and I don't have much knowledge about how to override / merge children components methods. 

Instead I changed the filter directly in the component, which worked great :)

**Comment by robrogers3** [comment]
Can you send me your code? (i.e. usage in App.vue)

The code that doesn’t work that is.

ps. You should be overriding the property for 'filter-by'

pps. Did you see my sample.?

**Comment by vellebelle** [comment]
Sure.. I tried the example you gave. This is in my App.vue template:

`      <vue-single-select 
              name="stockFinder"
              v-model="currentlySelectedCompany"
              :options='companies'              
              option-label="companyName"
              option-id="id"
              placeholder="ค้นหาบริษัทที่ต้องการลงทุนที่นี่"
              :max-results="120"
              :filterBy="filterBy"
       ></vue-single-select>`

And this is my method:

`filterBy: function(option) { 
      const searchText = this.$refs.select.searchText;
      return option.toString().toLowerCase().startsWith(searchText.toString().toLowerCase());
      }`

I am not sure exactly what the parameter option is supposed to be, but I am guessing that it is my array of options, so I tried this also:

` return this.companies.companyName.toString().toLowerCase().startsWith(searchText.toString().toLowerCase());`

With no luck. And as I mentioned I get an error when referring to `this.$refs.select.searchText`

When I console log it I get Uncaught TypeError: Cannot read property 'searchText' of undefined

Thanks

**Comment by robrogers3** [comment]
You don’t have a reference defined in your ‘html’.

<vue-single-select 
name="stockFinder” 
v-model="currentlySelectedCompany” 
:options='companies’ 
option-label="companyName” 
option-id="id” 
placeholder="ค้นหาบริษัทที่ต้องการลงทุนที่นี่” 
:max-results="120” 
:filterBy="filterBy” 
ref=“”select"
></vue-single-select>

https://vuejs.org/v2/guide/components-edge-cases.html#Accessing-Child-Component-Instances-amp-Child-Elements <https://vuejs.org/v2/guide/components-edge-cases.html#Accessing-Child-Component-Instances-amp-Child-Elements>
<base-input ref="usernameInput"></base-input>

this.$refs.usernameInput
<input ref="input">
And even define methods for use by the parent:
methods: {
  // Used to focus the input from the parent
  focus: function () {
    this.$refs.input.focus()
  }
}
Thus allowing the parent component to focus the input inside <base-input> with:
this.$refs.usernameInput.focus()

----------------------------------
Rob Rogers
415.615.2859
robrogers@me.com
----------------------------------

**Comment by vellebelle** [comment]
Than you for the clarification. I learned something new.. And it's working now..

Thanks again for this :)
