### ISSUE TITLE
How to make action like a stanrart html select?

### ISSUE THREAD

**Issue by alexdpts** [robrogers3/vue-single-select#7]
For example clear HTML:
`<select name="example">
	<option value="val1">peach</option>
	<option value="val2">pear</option>
</select>`
when i select peach, and submit form, i have example=val1.
When i use this component, and select peach i have 'peach' in fruit. 
How can i receive 'val1' in fruit?

**Comment by robrogers3** [comment]
I need to update my docs.

So, to be clear, you WANT the select options to be:
`<select name="example"> <option value="val1">peach</option> <option value="val2">pear</option> </select>
`
If so you should do something like this:
In App.vue:
`
<vue-single-select>
v-mode="fruit"
:options="fruits"
:option-key="value"
:option-label="name"
</vue-single-select>
<script>
data {
  fruit: null, // will become something like {key: 'val1', name: 'peach'}
  fruits: [
      {key: 'val1', name: 'peach'},
      {key: 'val2', name: 'pear'}
  ]
}
</script>
`
when you select an option, the value for 'fruit' will be {key: 'val1', name: 'peach'}
lemme know if that works.

**Comment by alexdpts** [comment]
thanks

**Comment by alexdpts** [comment]
Sorry, i was hurried to close issue.
i have an error "vue.min.js:6 ReferenceError: value is not defined" - linked to `:option-key="value"`

**Comment by robrogers3** [comment]
Please send me your code in App.vue. (or the parent component).
----------------------------------
Rob Rogers
415.615.2859
robrogers@me.com
----------------------------------

**Comment by alexdpts** [comment]
`<div id="app" class="container">
			<vue-single-select
			    v-model="language"
			    :options="languages"
			    :option-key="value"
				:option-label="name"
			></vue-single-select>
			<hr>
			{{ language.key }} | {{ language.name }}
        </div>
        
        <script>
            var app = new Vue({
                el: '#app',
                data () {
				    return {
						language: null,
         				languages: [{key: 'ru-RU', name: 'Русский'},{key: 'en-GB', name: 'English'}]
					}
				}
            });
        </script>`

**Comment by alexdpts** [comment]
`var app = new Vue({
                el: '#app',
                data () {
				    return {
						language: null,
         				languages: [{key: 'ru-RU', name: 'Русский'},{key: 'en-GB', name: 'English'}]
					}
				}
            });`

**Comment by robrogers3** [comment]
can you show me the ‘html’ for 

<vue-single-select>
----------------------------------
Rob Rogers
415.615.2859
robrogers@me.com
----------------------------------

**Comment by alexdpts** [comment]
`<vue-single-select
			    v-model="language"
			    :options="languages"
			    :option-key="value"
				:option-label="name"
			></vue-single-select>`

**Comment by robrogers3** [comment]
ok. you got it wrong, try:

> <vue-single-select v-model="language" :options="languages" :option-key=“key" :option-label="name" ></vue-single-select>
> 
----------------------------------
Rob Rogers
415.615.2859
robrogers@me.com
----------------------------------

**Comment by alexdpts** [comment]
vue.min.js:6 ReferenceError: key is not defined

**Comment by robrogers3** [comment]
I think you are defining the data section incorrectly.  your app.vue doesn’t look like a component. if that is the case then you need to define data as a object literal.

see: https://vuejs.org/v2/guide/instance.html <https://vuejs.org/v2/guide/instance.html>

it should look something like this:

data: {
  newTodoText: '',
  visitCount: 0,
  hideCompletedTodos: false,
  todos: [],
  error: null
}

you define it as a function.

my suggestion is to install the Vue helper for chrome dev tools, and reference the non-minimized version of the Vue.js
you can then inspect the data that the instance has available.

Actually my biggest suggestion is to watch this series. 
https://laracasts.com/series/learn-vue-2-step-by-step <https://laracasts.com/series/learn-vue-2-step-by-step>

-Rob
----------------------------------
Rob Rogers
415.615.2859
robrogers@me.com
----------------------------------

**Comment by alexdpts** [comment]
`var app = new Vue({
                el: '#app',
                data: {
					language: null,
					languages: [{key: 'ru-RU', name: 'Русский'},{key: 'en-GB', name: 'English'}]
				}
            });`
vue.min.js:6 ReferenceError: key is not defined

**Comment by robrogers3** [comment]
I’m not sure what’s going on.
your data looks fine.

please do what I mentioned below and watch this episode.
https://laracasts.com/series/learn-vue-2-step-by-step/episodes/2 <https://laracasts.com/series/learn-vue-2-step-by-step/episodes/2>

if you see this:
"Download the Vue Devtools for a better development experience:
https://github.com/vuejs/vue-devtools"
you do not have the chrome extension enabled.
----------------------------------
Rob Rogers
415.615.2859
robrogers@me.com
----------------------------------

**Comment by alexdpts** [comment]
I'm just starting to learn VUE and will definitely learn the lessons, thanks for the link.
I download Vue Devtools.
console:
`Property or method "key" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property`
`Property or method "name" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property`

**Comment by robrogers3** [comment]
yep. that’s your problem. the video will show you how to use the dev tool to figure out what data is available.

watching the videos will save you COUNTLESS hours.
----------------------------------
Rob Rogers
415.615.2859
robrogers@me.com
----------------------------------

**Comment by alexdpts** [comment]
errors is resolving by replace key on languages.key and name on languages.name in :option-key and :option-label declarations. 
But items list and result of selection looks fun
here is screenshot.
![vue-select](https://user-images.githubusercontent.com/17212759/49069510-dc255e80-f242-11e8-93a1-a9965084a3ae.jpg)

**Comment by robrogers3** [comment]
ok. what’s your code now?

have you watched the videos?
----------------------------------
Rob Rogers
415.615.2859
robrogers@me.com
----------------------------------

**Comment by alexdpts** [comment]
not yet. it's hard to me, but i catch key, by other way
